version: 0.2
phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
    - IMAGE_TAG=$(git describe --tags --abbrev=0)
    - echo tag $IMAGE_TAG
    - IMAGE_NAME=$REPOSITORY_URI/$IMAGE_REPO_NAME/hydra
    - echo image $IMAGE_NAME
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t $IMAGE_NAME -t $IMAGE_NAME:$IMAGE_TAG .
  post_build:
    commands:
    - echo Build completed on `date`
    - echo pushing to repo
    # update the following line with the URI of your own ECR repository
    - docker push --all-tags $IMAGE_NAME
